# Task 1

In [1]:
!pip install requests pandas sqlalchemy

import requests
import pandas as pd
from dotenv import load_dotenv
import os

load_dotenv()
API_KEY = "1bf423433a947428e6a3e3ec968395bc"

print(API_KEY)

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
1bf423433a947428e6a3e3ec968395bc

In [2]:
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

url = "http://api.themoviedb.org/3/movie/popular"
params = {"api_key": API_KEY}

response = requests.get(url, params=params, timeout=10, verify=False)
print(response.status_code)

200

In [3]:
import pandas as pd

data = response.json()

movies = data['results']

df = pd.DataFrame(movies)

df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/1x9e0qWonw634NhIsRdvnneeqvN.jpg,"[10749, 18]",1523145,en,Твоё сердце будет разбито,High school student Polina is saved from bully...,1165.1266,/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg,2026-03-26,Your Heart Will Be Broken,False,6.896,24
1,False,/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg,"[878, 12, 14]",83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,503.6662,/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg,2025-12-17,Avatar: Fire and Ash,False,7.300,2066
2,False,/uNToXatdunyvWXyXMrTI1nLvh6r.jpg,"[35, 878, 80]",1115544,en,Mike & Nick & Nick & Alice,Two gangsters and the woman they love try to s...,352.9397,/7F0jc75HrSkLVcvOXR2FXAIwuEv.jpg,2026-03-14,Mike & Nick & Nick & Alice,False,6.706,107
3,False,/6GuqUJ33BnWDAoVPZP55gDr5G55.jpg,"[28, 53, 10402]",1084187,en,Pretty Lethal,A troupe of ballerinas find themselves fightin...,311.0726,/znTPnXCK3lEQJgqXCvP7e5FUz6f.jpg,2026-03-13,Pretty Lethal,False,6.744,156
4,False,/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg,"[16, 35, 10751]",1297842,en,GOAT,A small goat with big dreams gets a once-in-a-...,297.8194,/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg,2026-02-11,GOAT,False,7.740,248

In [4]:
print(response.status_code)
print(response.json())

200
{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/1x9e0qWonw634NhIsRdvnneeqvN.jpg', 'genre_ids': [10749, 18], 'id': 1523145, 'original_language': 'en', 'original_title': 'Твоё сердце будет разбито', 'overview': 'High school student Polina is saved from bullying at her new school and makes a deal with the main bully Bars: he must pretend to be her boyfriend and protect her, and she must do everything he says. During this game, the couple develops real feelings, but her family and classmates have reasons to separate the lovers.', 'popularity': 1165.1266, 'poster_path': '/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg', 'release_date': '2026-03-26', 'title': 'Your Heart Will Be Broken', 'video': False, 'vote_average': 6.896, 'vote_count': 24}, {'adult': False, 'backdrop_path': '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg', 'genre_ids': [878, 12, 14], 'id': 83533, 'original_language': 'en', 'original_title': 'Avatar: Fire and Ash', 'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.", 'popularity': 503.6662, 'poster_path': '/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg', 'release_date': '2025-12-17', 'title': 'Avatar: Fire and Ash', 'video': False, 'vote_average': 7.3, 'vote_count': 2066}, {'adult': False, 'backdrop_path': '/uNToXatdunyvWXyXMrTI1nLvh6r.jpg', 'genre_ids': [35, 878, 80], 'id': 1115544, 'original_language': 'en', 'original_title': 'Mike & Nick & Nick & Alice', 'overview': 'Two gangsters and the woman they love try to survive the most dangerous night of their lives. As if that wasn’t enough, there’s one wild ingredient added to the mix: a time machine.', 'popularity': 352.9397, 'poster_path': '/7F0jc75HrSkLVcvOXR2FXAIwuEv.jpg', 'release_date': '2026-03-14', 'title': 'Mike & Nick & Nick & Alice', 'video': False, 'vote_average': 6.706, 'vote_count': 107}, {'adult': False, 'backdrop_path': '/6GuqUJ33BnWDAoVPZP55gDr5G55.jpg', 'genre_ids': [28, 53, 10402], 'id': 1084187, 'original_language': 'en', 'original_title': 'Pretty Lethal', 'overview': 'A troupe of ballerinas find themselves fighting for survival as they attempt to escape from a remote inn after their bus breaks down on the way to a dance competition.', 'popularity': 311.0726, 'poster_path': '/znTPnXCK3lEQJgqXCvP7e5FUz6f.jpg', 'release_date': '2026-03-13', 'title': 'Pretty Lethal', 'video': False, 'vote_average': 6.744, 'vote_count': 156}, {'adult': False, 'backdrop_path': '/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg', 'genre_ids': [16, 35, 10751], 'id': 1297842, 'original_language': 'en', 'original_title': 'GOAT', 'overview': 'A small goat with big dreams gets a once-in-a-lifetime shot to join the pros and play roarball, a high-intensity, co-ed, full-contact sport dominated by the fastest, fiercest animals in the world.', 'popularity': 297.8194, 'poster_path': '/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg', 'release_date': '2026-02-11', 'title': 'GOAT', 'video': False, 'vote_average': 7.74, 'vote_count': 248}, {'adult': False, 'backdrop_path': '/nHxWyy18SvAZ8jJeemtS8k1UNjM.jpg', 'genre_ids': [28, 80, 53], 'id': 1290821, 'original_language': 'en', 'original_title': 'Shelter', 'overview': 'A man living in self-imposed exile on a remote island rescues a young girl from a violent storm, setting off a chain of events that forces him out of seclusion to protect her from enemies tied to his past.', 'popularity': 308.3847, 'poster_path': '/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg', 'release_date': '2026-01-28', 'title': 'Shelter', 'video': False, 'vote_average': 6.754, 'vote_count': 439}, {'adult': False, 'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg', 'genre_ids': [878, 12], 'id': 687163, 'original_language': 'en', 'original_title': 'Project Hail Mary', 'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction… but an unexpected friendship means he may not have to do it alone.', 'popularity': 267.0607, 'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg', 'release_date': '2026-03-15', 'title': 'Project Hail Mary', 'video': False, 'vote_average': 8.193, 'vote_count': 844}, {'adult': False, 'backdrop_path': '/hz7TdCrpLLt2Dz7S3PS2HG9rpAO.jpg', 'genre_ids': [27, 9648, 80], 'id': 1159559, 'original_language': 'en', 'original_title': 'Scream 7', 'overview': 'When a new Ghostface killer emerges in the quiet town where Sidney Prescott has built a new life, her darkest fears are realized as her daughter becomes the next target. Determined to protect her family, Sidney must face the horrors of her past to put an end to the bloodshed once and for all.', 'popularity': 238.6168, 'poster_path': '/jjyuk0edLiW8vOSnlfwWCCLpbh5.jpg', 'release_date': '2026-02-25', 'title': 'Scream 7', 'video': False, 'vote_average': 5.813, 'vote_count': 524}, {'adult': False, 'backdrop_path': '/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg', 'genre_ids': [27, 53, 35], 'id': 1198994, 'original_language': 'en', 'original_title': 'Send Help', 'overview': "Two colleagues become stranded on a deserted island, the only survivors of a plane crash. On the island, they must overcome past grievances and work together to survive, but ultimately, it's a battle of wills and wits to make it out alive.", 'popularity': 191.3203, 'poster_path': '/mjkS2iAgWj3ik1DTjvI15nHZ7yl.jpg', 'release_date': '2026-01-22', 'title': 'Send Help', 'video': False, 'vote_average': 7.094, 'vote_count': 754}, {'adult': False, 'backdrop_path': '/kKF4gEiBDArhONlCcunHVgBp3bA.jpg', 'genre_ids': [80, 53], 'id': 1171145, 'original_language': 'en', 'original_title': 'Crime 101', 'overview': 'When an elusive thief whose high-stakes heists unfold along the iconic 101 freeway in Los Angeles eyes the score of a lifetime, with hopes of this being his final job, his path collides with a disillusioned insurance broker who is facing her own crossroads. Determined to crack the case, a relentless detective closes in on the operation, raising the stakes even higher.', 'popularity': 178.7456, 'poster_path': '/tVvpFIoteRHNnoZMhdnwIVwJpCA.jpg', 'release_date': '2026-02-11', 'title': 'Crime 101', 'video': False, 'vote_average': 7.0, 'vote_count': 225}, {'adult': False, 'backdrop_path': '/wns4x1GyxCudgOZRyhXKjXVJf3T.jpg', 'genre_ids': [12, 53, 878], 'id': 840464, 'original_language': 'en', 'original_title': 'Greenland 2: Migration', 'overview': 'Having found the safety of the Greenland bunker after the comet Clarke decimated the Earth, the Garrity family must now risk everything to embark on a perilous journey across the wasteland of Europe to find a new home.', 'popularity': 183.024, 'poster_path': '/z2tqCJLsw6uEJ8nJV8BsQXGa3dr.jpg', 'release_date': '2026-01-07', 'title': 'Greenland 2: Migration', 'video': False, 'vote_average': 6.495, 'vote_count': 770}, {'adult': False, 'backdrop_path': '/1fkuBPid72KGS6WmtkEXMftZtkE.jpg', 'genre_ids': [80, 18], 'id': 875828, 'original_language': 'en', 'original_title': 'Peaky Blinders: The Immortal Man', 'overview': 'After his estranged son gets embroiled in a Nazi plot, self-exiled gangster Tommy Shelby must return to Birmingham to save his family — and his nation.', 'popularity': 165.1928, 'poster_path': '/gRMalasZEzsZi4w2VFuYusfSfqf.jpg', 'release_date': '2026-03-05', 'title': 'Peaky Blinders: The Immortal Man', 'video': False, 'vote_average': 7.319, 'vote_count': 596}, {'adult': False, 'backdrop_path': '/6yeVcxFR0j08vlv2OlL6zbewm4D.jpg', 'genre_ids': [28, 878, 53], 'id': 1265609, 'original_language': 'en', 'original_title': 'War Machine', 'overview': 'On one last grueling mission during Army Ranger training, a combat engineer must lead his unit in a fight against a giant otherworldly killing machine.', 'popularity': 179.5612, 'poster_path': '/tlPgDzwIE7VYYIIAGCTUOnN4wI1.jpg', 'release_date': '2026-02-12', 'title': 'War Machine', 'video': False, 'vote_average': 7.277, 'vote_count': 1256}, {'adult': False, 'backdrop_path': '/61RYedFgX1K07xgVIvdJzukSR4g.jpg', 'genre_ids': [35, 18, 10751, 10749], 'id': 848116, 'original_language': 'hi', 'original_title': 'रॉकी और रानी की प्रेम कहानी', 'overview': "Gym-freak brat Rocky falls in love with Rani, who comes from a well-educated Bengali family. Being from polar opposite worlds, the two decide to switch their families to adjust to each other's cultures and backgrounds and to know if their marriage will survive. Rocky and Rani are trapped in a world where they are united by love but divided by families and the ultimate question is will they fit in?", 'popularity': 158.1775, 'poster_path': '/vTQIqlxUkOuyf2UKhlM2OUaFGKz.jpg', 'release_date': '2023-07-28', 'title': 'Rocky Aur Rani Kii Prem Kahaani', 'video': False, 'vote_average': 6.045, 'vote_count': 78}, {'adult': False, 'backdrop_path': '/lgotja3xMoJZbynwHfcQcJAEMWH.jpg', 'genre_ids': [16, 35, 12, 10751, 9648], 'id': 1084242, 'original_language': 'en', 'original_title': 'Zootopia 2', 'overview': "After cracking the biggest case in Zootopia's history, rookie cops Judy Hopps and Nick Wilde find themselves on the twisting trail of a great mystery when Gary De'Snake arrives and turns the animal metropolis upside down. To crack the case, Judy and Nick must go undercover to unexpected new parts of town, where their growing partnership is tested like never before.", 'popularity': 123.8365, 'poster_path': '/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg', 'release_date': '2025-11-26', 'title': 'Zootopia 2', 'video': False, 'vote_average': 7.6, 'vote_count': 2407}, {'adult': False, 'backdrop_path': '/vSQSYd2zZTqc0zmHImwWEGGluMI.jpg', 'genre_ids': [10749, 18], 'id': 1316092, 'original_language': 'en', 'original_title': '"Wuthering Heights"', 'overview': 'Tragedy strikes when Heathcliff falls in love with Catherine Earnshaw, a woman from a wealthy family in 18th-century England.', 'popularity': 131.7118, 'poster_path': '/lGlJ2cTDwMacj5nuANd38UjVGNQ.jpg', 'release_date': '2026-02-11', 'title': '"Wuthering Heights"', 'video': False, 'vote_average': 6.4, 'vote_count': 608}, {'adult': False, 'backdrop_path': '/8zyQbsmMlXfLkcctjNz5YZZwpkw.jpg', 'genre_ids': [27], 'id': 999136, 'original_language': 'en', 'original_title': 'Do Not Enter', 'overview': 'A group of young explorers investigates an old abandoned hotel, only to encounter a strange supernatural being and a competing group looking for a legendary hidden treasure.', 'popularity': 116.1007, 'poster_path': '/stM9N7eJmHKLmFR59JG4tLdN7Wk.jpg', 'release_date': '2026-03-19', 'title': 'Do Not Enter', 'video': False, 'vote_average': 5.2, 'vote_count': 44}, {'adult': False, 'backdrop_path': '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg', 'genre_ids': [16, 10751, 878, 35, 12], 'id': 1327819, 'original_language': 'en', 'original_title': 'Hoppers', 'overview': "Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.", 'popularity': 129.5723, 'poster_path': '/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg', 'release_date': '2026-03-04', 'title': 'Hoppers', 'video': False, 'vote_average': 7.556, 'vote_count': 355}, {'adult': False, 'backdrop_path': '/yJi6g0CnsqANLNuVaRX28tZxeHX.jpg', 'genre_ids': [27, 9648], 'id': 1193501, 'original_language': 'en', 'original_title': 'Whistle', 'overview': 'A misfit group of unwitting high school students stumble upon a cursed object, an ancient Aztec Death Whistle. They discover that blowing the whistle and the terrifying sound it emits will summon their future deaths to hunt them down.', 'popularity': 101.3404, 'poster_path': '/eGxPyseSnEZBMJaopGfRUO9HSYx.jpg', 'release_date': '2026-01-20', 'title': 'Whistle', 'video': False, 'vote_average': 5.976, 'vote_count': 207}, {'adult': False, 'backdrop_path': '/7uXzE0ZBkbAeKylOz7cUQF4Yw75.jpg', 'genre_ids': [18], 'id': 879945, 'original_language': 'nl', 'original_title': "L'homme inconnu", 'overview': 'Louis, a Flemish writer, decides to isolate himself at the Côte d’Azur, hoping this place will bring him inspiration.', 'popularity': 158.7154, 'poster_path': '/4TpBhdaSl5ALHbgeaYOLF8Q3haz.jpg', 'release_date': '2021-10-16', 'title': 'The Unknown Man', 'video': False, 'vote_average': 8.5, 'vote_count': 2}], 'total_pages': 55942, 'total_results': 1118827}

In [5]:
df['genre_ids'] = df['genre_ids'].astype(str)

In [6]:
from sqlalchemy import create_engine

engine = create_engine('sqlite:///movies.db')

df.to_sql("movies", con=engine, if_exists="replace", index=False)

20

## Task 2

In [7]:
df = pd.read_sql("SELECT * FROM movies", con=engine)
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,0,/1x9e0qWonw634NhIsRdvnneeqvN.jpg,"[10749, 18]",1523145,en,Твоё сердце будет разбито,High school student Polina is saved from bully...,1165.1266,/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg,2026-03-26,Your Heart Will Be Broken,0,6.896,24
1,0,/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg,"[878, 12, 14]",83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,503.6662,/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg,2025-12-17,Avatar: Fire and Ash,0,7.300,2066
2,0,/uNToXatdunyvWXyXMrTI1nLvh6r.jpg,"[35, 878, 80]",1115544,en,Mike & Nick & Nick & Alice,Two gangsters and the woman they love try to s...,352.9397,/7F0jc75HrSkLVcvOXR2FXAIwuEv.jpg,2026-03-14,Mike & Nick & Nick & Alice,0,6.706,107
3,0,/6GuqUJ33BnWDAoVPZP55gDr5G55.jpg,"[28, 53, 10402]",1084187,en,Pretty Lethal,A troupe of ballerinas find themselves fightin...,311.0726,/znTPnXCK3lEQJgqXCvP7e5FUz6f.jpg,2026-03-13,Pretty Lethal,0,6.744,156
4,0,/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg,"[16, 35, 10751]",1297842,en,GOAT,A small goat with big dreams gets a once-in-a-...,297.8194,/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg,2026-02-11,GOAT,0,7.740,248

In [8]:
df.describe()

       adult            id   popularity  video  vote_average   vote_count
count   20.0  2.000000e+01    20.000000   20.0     20.000000    20.000000
mean     0.0  1.062134e+06   263.099260    0.0      6.930400   585.500000
std      0.0  3.097655e+05   234.540901    0.0      0.811701   655.930556
min      0.0  8.353300e+04   101.340400    0.0      5.200000     2.000000
25%      0.0  8.789158e+05   151.561075    0.0      6.471250   143.750000
50%      0.0  1.137552e+06   181.292600    0.0      6.948000   397.000000
75%      0.0  1.271912e+06   300.460725    0.0      7.378250   758.000000
max      0.0  1.523145e+06  1165.126600    0.0      8.500000  2407.000000

In [9]:
df.isnull().sum()

adult                0
backdrop_path        0
genre_ids            0
id                   0
original_language    0
original_title       0
overview             0
popularity           0
poster_path          0
release_date         0
title                0
video                0
vote_average         0
vote_count           0
dtype: int64